server:
  port: 8888
  tomcat:
    connection-timeout: 20000
    acceptCount: 500
    threads:
      max: 400
netty:
  port: 9000
spring:
  application:
    name: dubbo-netty-websocket
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1000MB
      # 一次传多个文件的总大小
      max-request-size: 1000MB
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    timeout: 30000
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        ax-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

dubbo:
  consumer:
    check: false
    retries: 0
    timeout: 10000
  protocol:
    name: dubbo
    port: -1
  provider:
    retries: 0
    timeout: 10000
  registry:
    address: nacos://localhost:8848
    check: false
  scan:
    base-packages: com.glasssix.dubbo
